// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2uAmaHU6ZB0Wh0mlCtyRYJas7_wH93YQ',
    appId: '1:212109007704:web:77e0319b9c434e1184232d',
    messagingSenderId: '212109007704',
    projectId: 'ecommerce-app-f4d2f',
    authDomain: 'ecommerce-app-f4d2f.firebaseapp.com',
    storageBucket: 'ecommerce-app-f4d2f.firebasestorage.app',
    measurementId: 'G-VLMD2BBBEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs8SmcERjB1kpbeN84b3w_oaHFU9Yoy-0',
    appId: '1:212109007704:android:29d224ec6e1f414b84232d',
    messagingSenderId: '212109007704',
    projectId: 'ecommerce-app-f4d2f',
    storageBucket: 'ecommerce-app-f4d2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLBGi1hSyUVrZiw-5he1Oofy3-UN6038A',
    appId: '1:212109007704:ios:4a0c5450cd22b8b784232d',
    messagingSenderId: '212109007704',
    projectId: 'ecommerce-app-f4d2f',
    storageBucket: 'ecommerce-app-f4d2f.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLBGi1hSyUVrZiw-5he1Oofy3-UN6038A',
    appId: '1:212109007704:ios:4a0c5450cd22b8b784232d',
    messagingSenderId: '212109007704',
    projectId: 'ecommerce-app-f4d2f',
    storageBucket: 'ecommerce-app-f4d2f.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2uAmaHU6ZB0Wh0mlCtyRYJas7_wH93YQ',
    appId: '1:212109007704:web:3cbdf8387674ca2e84232d',
    messagingSenderId: '212109007704',
    projectId: 'ecommerce-app-f4d2f',
    authDomain: 'ecommerce-app-f4d2f.firebaseapp.com',
    storageBucket: 'ecommerce-app-f4d2f.firebasestorage.app',
    measurementId: 'G-E9R3046H0Y',
  );
}
